#!/usr/bin/env python

import sys
import shpshift
from optparse import OptionParser

def invalid_opts(parser):
    parser.print_help(sys.stderr)
    sys.exit(1)

def print_error(msg):
    sys.stdout.write(msg)
    sys.stdout.write("\n")
    sys.exit(1)

def get_header(parser, options):
    if options.header_auto:
        # if conflicting header options are given, throw an error
        if not options.header is None:
            invalid_opts(parser)
        else:
            # if autodetect flag is explicitly passed
            return shpshift.Header.AUTODETECT
    else:
        if options.header is None:
            # default case, if no flags are passed
            return shpshift.Header.AUTODETECT
        else:
            # which non-autodetect header flag was passed?
            return shpshift.Header.FIRSTROW if options.header else shpshift.Header.NONE

def parse_options():
    usage = "usage: %prog [options] [INPUTFILE] OUTPUTFILE"
    version = "%prog " + shpshift.VERSION
    parser = OptionParser(usage=usage, version=version)

    parser.add_option("-f", "--force",
                       action="store_true", dest="overwrite", default=False,
                       help="force overwriting of output files")
    
    parser.add_option("-s", "--sheet-index",
                       action="store", dest="sheetnum", default=0, type="int",
                       help="index of the sheet to convert, starting from 0 (defaults to 0)")

    parser.add_option("-l", "--leading-header", 
                      action="store_true", dest="header", default=None,
                      help="leading row of the spreadsheet is a header")
    parser.add_option("-n", "--no-header", 
                      action="store_false", dest="header",
                      help="leading row of the spreadsheet is not a header")
    parser.add_option("-d", "--detect-header", 
                      action="store_true", dest="header_auto", default=False,
                      help="try to detect if the leading row of the spreadsheet is a header [default]")

    (options, args) = parser.parse_args()
    return (parser, options, args)

if __name__ == '__main__':

    (parser, options, args) = parse_options()
    header = get_header(parser, options)

    if options.sheetnum < 0:
        print_error("sheet number must be greater than zero")

    # ensure we have the REQUIRED arguments we expect
    if len(args) == 1:
        output_filename = args[0]
        xlfile = sys.stdin.read()
    elif len(args) == 2:
        output_filename = args[1]
        try:
            with open(args[0], "rb") as f:
                xlfile = f.read()
        except IOError, e:
            print_error("could not read file '%s': %s" % (
                    args[0], str(e)))
    else:
        invalid_opts(parser)

    try:
        reader = shpshift.XlsReader(file_contents=xlfile, header=header, sheet_number=options.sheetnum)
    except ValueError, e:
        print_error("problem reading spreadsheet: %s" % str(e))


    print reader.fields()
